# Source: https://github.com/v2fly/domain-list-community/blob/master/data/netlify
# domain: 4
# full: 1
# keyword: 0
# regexp: 0 (not in rule-set)


payload:
  - DOMAIN-SUFFIX,bitballoon.com
  - DOMAIN-SUFFIX,netlify.app
  - DOMAIN-SUFFIX,netlify.com
  - DOMAIN-SUFFIX,netlifystatus.com
  - DOMAIN,d33wubrfki0l68.cloudfront.net