# Source: https://github.com/v2fly/domain-list-community/blob/master/data/snapcraft
# domain: 2
# full: 0
# keyword: 0
# regexp: 0 (not in rule-set)


payload:
  - DOMAIN-SUFFIX,snapcraft.io
  - DOMAIN-SUFFIX,snapstore.io