name: Convert V2Ray rules to AdGuard rules
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    name: Build and Convert
    runs-on: ubuntu-latest

    steps:
      - name: Checkout v2fly/domain-list-community
        uses: actions/checkout@v3
        with:
          repository: v2fly/domain-list-community
          path: workspace
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set variables
        run: |
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
        shell: bash
      - name: Generate plaintext and Convert to rules
        run: |
          cd workspace || exit 1
          curl -OL https://raw.githubusercontent.com/rootmelo92118/v2ray-rules-adguard/master/GenerateAndConvert.py
          mkdir AdGuard_Rule
          python3 GenerateAndConvert.py
          mv AdGuard_Rule ../
          cd ../ && rm -rf workspace
          rm AdGuard_Rule/dlc.dat
