name: Convert V2Ray rules to AdGuard rules
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    name: Build and Convert
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
        with:
          path: workspace
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set variables
        run: |
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
        shell: bash
      - name: Generate plaintext and Convert to rules
        run: |
          cd workspace || exit 1
          mkdir AdGuard_Rule
          python3 GenerateAndConvert.py
          mv Adguard_Rule ../
          cd ../ && rm -rf workspace
